steps:
# Original
# https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/cloudbuild.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # File that contains failures.
    failure_file=failure.log
    touch ${failure_file}

    # Loop through the builders, and build independently.
    for f in $(find . -mindepth 2 -type f -name 'cloudbuild.yaml');
    do
      echo "Building ${f%/*} ... "
      (
        gcloud alpha builds submit ${f%/*} --config=${f} --gcs-log-dir="$_GCS_LOG_DIR" 2>&1 > /dev/null
        if [[ $? -ne 0 ]]; then
          echo "${f%/*} failed" >> ${failure_file}
        fi
      ) &
    done
    wait

    # Check if there is any failure.
    if [[ -s ${failure_file} ]]; then
      echo "Some builds failed:"
      cat ${failure_file}
      echo "Exiting."
      exit 1
    fi
    echo "All builds succeeded."
tags: ['cloud-builder']
options:
 machineType: 'N1_HIGHCPU_8'
